[package]
name = "pmrustcli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.0.0-beta.2"
serde = "1.0.117"
dirs = "1.0.5"